using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TheBookCave.Data;
using TheBookCave.Data.EntityModels.BookEntityModel;
using TheBookCave.Models;

namespace TheBookCave
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = BuildWebHost(args);
            SeedData();
            host.Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();

        public static void SeedData()
        {
            var db = new DataContext();

            if(db.Books.Any())
            {
                var initialBooks = new List<BookEntityModel>()
                {
                    new BookEntityModel { Title = "Mein Kampf", Author = "Adolf Hitler", ISBN10 = "817224164X", ISBN13 = "9788172241643", Description = "Book Description In 1922, just four years after the war to end all wars, an unknown Austrian then living in Bavaria planned a pamphlet to be called Settling Accounts. In it he intended to attack the ineffectiveness of the dominant political parties in Germany which were opposed to the new National Socialists (Nazis). In November 1923, Adolf Hitler was jailed for the abortive Munich Beer Hall putsch along with men willing and able to assist him with his writing. With the help of these collaborators, chief among them Rudolf Hess, the pamphlet became a book. Settling Accounts became Mein Kampf, an unparalleled example of muddled economics and history, appalling bigotry, and an intense self-glorification of Adolf Hitler as the true founder and builder of the National Socialist movement. It was written in hate and it contained a blueprint for violent bloodshed. When Mein Kampf was published in 1925, it was a failure. In 1926 a second volume appeared - it was no more successful than the first. People either laughed at it or ignored it. They were wrong to do so. As Hitler's power increased, pressure was put on all party members to buy the book. Gradually this pressure was extended to all elements of the German population. Soon Mein Kampf was even being passed out to newlywed couples as a gift.", NumberOfPages = 524, DatePublished = new DateModel(2000, 01, 21), Publisher = "Jaico Publishing House", Rating = 4.5, NumberOfRatings = 13, NumberOfCopiesSold = 88, InStock = 94, Genre="Biography", Price = 13.99},
                    new BookEntityModel { Title = "Therese Raquin", Author = "Emile Zola", ISBN10 = "0199536856", ISBN13 = "9780199536856", Description = "Therese Raquin is a clinically observed, sinister tale of adultery and murder among the lower orders in nineteenth-century Paris. Zola's dispassionate dissection of the motivations of his characters, mere 'human beasts' who kill in order to satisfy their lust, is much more than an atmospheric Second Empire period-piece. Many readers were scandalized by an approach to character-drawing which seemed to undermine not only the moral values of a deeply conservative society, but also the whole code of psychological description on which the realist novel was based. Together with the important 'Preface to the Second Edition' in which Zola defended himself against charges of immorality, Therese Raquin stands as a key early manifesto of the French Naturalist movement, of which Zola was the founding father. Even today, this novel has lost none of its power to shock. This new translation is based on the second edition of 1868. The Introduction situates the novel in the context of Naturalism, medicine, and the scientific ideas of Zola's day. ABOUT THE SERIES: For over 100 years Oxford World's Classics has made available the widest range of literature from around the globe.", NumberOfPages = 256, DatePublished = new DateModel(2009, 24, 01), Publisher = "Oxford University Press", Rating = 3.5, NumberOfRatings = 17, NumberOfCopiesSold = 39, InStock = 73, Genre="Fantasy", Price = 7.99},
                    new BookEntityModel { Title = "The Naked and the Dead", Author = "Norman Mailer", ISBN10 = "0007204957", ISBN13 = "9780007204953", Description = "Focusing on the experiences of a fourteen-man platoon stationed on a Japanese-held island in the South Pacific during World War II, and written in a journalistic style, it tells the moving story of the soldiers' struggle to retain a sense of dignity amidst the horror of warfare, and to find a source of meaning in their lives amisdst the sounds and fury of battle. ", NumberOfPages = 720, DatePublished = new DateModel(2010, 02, 01), Publisher = "HarperCollins Publishers", Rating = 4.0, NumberOfRatings = 18, NumberOfCopiesSold = 20, InStock = 9, Genre="War", Price = 14.99},
                    new BookEntityModel { Title = "The Magic Toyshop", Author = "Angela Carter ", ISBN10 = "0860681904", ISBN13 = "9780860681908", Description = "To the red-haired, dancing Finn, the gentle Francie, dumb Aunt Margaret and Uncle Phillip. Francie plays curious night music, Finn kisses fifteen-year-old Melanie in the mysterious ruins of the pleasure gardens. Brooding over all is Uncle Philip: Uncle Philip, with blank eyes the colour of wet newspaper, making puppets the size of men, and clockwork roses. He loves his magic puppets, but hates the love of man for woman, boy for girl, brother for sister... ", NumberOfPages = 208, DatePublished = new DateModel(1992, 08, 27), Publisher = "Little, Brown Book Group", Rating = 4.0, NumberOfRatings = 12, NumberOfCopiesSold = 23, InStock = 65, Genre="Fantasy", Price = 6.99},
                    new BookEntityModel { Title = "Northern Lights", Author = "Philip Pullman", ISBN10 = "1407130226", ISBN13 = "9781407130224", Description = "\"Without this child, we shall all die.\" Lyra Belacqua and her animal daemon live half-wild and carefree among scholars of Jordan College, Oxford. The destiny that awaits her will take her to the frozen lands of the Arctic, where witch-clans reign and ice-bears fight. Her extraordinary journey will have immeasurable consequences far beyond her own world... ", NumberOfPages = 448, DatePublished = new DateModel(2011, 04, 01), Publisher = "Scholastic", Rating = 4.0, NumberOfRatings = 23, NumberOfCopiesSold = 151, InStock = 49, Genre="Children", Price = 7.99},
                    new BookEntityModel { Title = "Rebecca", Author = "Daphne du Maurier", ISBN10 = "1844080382", ISBN13 = "9781844080380", Description = "Working as a lady's companion, the orphaned heroine of Rebecca learns her place. Life begins to look very bleak until, on a trip to the South of France, she meets Maxim de Winter, a handsome widower whose sudden proposal of marriage takes her by surprise. Whisked from glamorous Monte Carlo to his brooding estate, Manderley, on the Cornish Coast, the new Mrs de Winter finds Max a changed man. And the memory of his dead wife Rebecca is forever kept alive by the forbidding Mrs Danvers . . . ", NumberOfPages = 448, DatePublished = new DateModel(2003, 01, 30), Publisher = "Little, Brown Book Group", Rating = 4.0, NumberOfRatings = 13, NumberOfCopiesSold = 20, InStock = 50, Genre="Fantasy", Price = 5.99},
                    new BookEntityModel { Title = "Franny and Zooey", Author = "J. D. Salinger", ISBN10 = "0241950449", ISBN13 = "9780241950449", Description = "Franny Glass and Lane Coutell are the perfect campus couple: beautiful, intelligent, their whole lives ahead of them. But one weekend when Franny is visiting, amid the excitement of the big Yale game, something goes wrong and tensions begin to surface. Are they really such a perfect match after all? Franny's older brother is Zooey. They come from a sophisticated yet highly eccentric family: all seven Glass siblings are former child stars, all strange and enchanting and damaged in their own way. And when Franny's anxiety spirals into a full-blown breakdown, Zooey is the only one who might be able to save her. ", NumberOfPages = 160, DatePublished = new DateModel(2010, 05, 01), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 43, NumberOfCopiesSold = 90, InStock = 70, Genre="Fantasy", Price = 8.99},
                    new BookEntityModel { Title = "Story of the Eye", Author = "Georges Bataille", ISBN10 = "0872862097", ISBN13 = "9780872862098", Description = "In 1928, Georges Bataille published this first novel under a pseudonym, a legendary shocker that uncovers the dark side of the erotic by means of forbidden obsessive fantasies of excess and sexual extremes. A classic of pornographic literature, Story of the Eye finds the parallels in Sade and Nietzsche and in the investigations of contemporary psychology; it also forecasts Bataille's own theories of ecstasy, death and transgression which he developed in later work. ", NumberOfPages = 103, DatePublished = new DateModel(1997, 08, 03), Publisher = "City Lights Books", Rating = 3.5, NumberOfRatings = 17, NumberOfCopiesSold = 47, InStock = 13, Genre="Romance", Price = 8.99},
                    new BookEntityModel { Title = "Journey to the End of the Night", Author = "Louis-Ferdinand Celine", ISBN10 = "0811216543", ISBN13 = "9780811216548", Description = "Louis-Ferdinand Celine's revulsion and anger at what he considered the idiocy and hypocrisy of society explodes from nearly every page of this novel. Filled with slang and obscenities and written in raw, colloquial language, Journey to the End of the Night is a literary symphony of violence, cruelty and obscene nihilism. This book shocked most critics when it was first published in France in 1932, but quickly became a success with the reading public in Europe, and later in America where it was first published by New Directions in 1952. The story of the improbable yet convincingly described travels of the petit-bourgeois (and largely autobiographical) antihero, Bardamu, from the trenches of World War I, to the African jungle, to New York and Detroit, and finally to life as a failed doctor in Paris, takes the readers by the scruff and hurtles them toward the novel's inevitable, sad conclusion. ", NumberOfPages = 464, DatePublished = new DateModel(2006, 06, 02), Publisher = "New Directions Publishing Corporation", Rating = 4.0, NumberOfRatings = 16, NumberOfCopiesSold = 54, InStock = 44, Genre="Fantasy", Price = 15.99},
                    new BookEntityModel { Title = "Alice's Adventures in Wonderland and Through the Looking Glass", Author = "Lewis Carroll", ISBN10 = "0141439769", ISBN13 = "9780141439761", Description = "Conjured up one 'golden afternoon' in 1862 to entertain Alice Liddell, the daughter of the dean of Carroll's college, the dream worlds of nonsensical Wonderland and back-to-front Looking-Glass kingdom depict order turned upside-down. Following the white rabbit into his warren, Alice falls into a world where croquet is played with hedgehogs and flamingos, a baby turns into a pig, time runs amok at a the Mad Hatter's tea-party, a chaotic game of chess makes Alice a Queen and the Mock Turtle and Gryphon dance the Lobster Quadrille. But amongst the anarchic humour and sparkling wordplay, unforgettable characters, puzzles and riddles, are poignant moments of nostalgia for a lost childhood. Original and experimental, adapted into countless film and television versions as Alice in Wonderland, the Alice books give readers a window on both child and adult worlds.", NumberOfPages = 448, DatePublished = new DateModel(2008, 24, 23), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 19, NumberOfCopiesSold = 20, InStock = 8, Genre="Fantasy", Price = 8.99},
                    new BookEntityModel { Title = "A Suitable Boy", Author = "Vikram Seth", ISBN10 = "1780227892", ISBN13 = "9781780227894", Description = "Vikram Seth's novel is, at its core, a love story: the tale of Lata - and her mother's - attempts to find her a suitable husband, through love or through exacting maternal appraisal. At the same time, it is the story of India, newly independent and struggling through a time of crisis as a sixth of the world's population faces its first great general election and the chance to map its own destiny. ", NumberOfPages = 1504, DatePublished = new DateModel(2013, 11, 21), Publisher = "Orion Publishing Co", Rating = 4.0, NumberOfRatings = 14, NumberOfCopiesSold = 20, InStock = 7, Genre="Fantasy", Price = 14.99},
                    new BookEntityModel { Title = "Midnight's Children", Author = "Salman Rushdie", ISBN10 = "0099578514", ISBN13 = "9780099578512", Description = "Born at the stroke of midnight, at the precise moment of India's independence, Saleem Sinai is destined from birth to be special. For he is one of 1,001 children born in the midnight hour, children who all have special gifts, children with whom Saleem is telepathically linked. But there has been a terrible mix up at birth, and Saleem's life takes some unexpected twists and turns. As he grows up amidst a whirlwind of triumphs and disasters, Saleem must learn the ominous consequences of his gift, for the course of his life is inseparably linked to that of his motherland, and his every act is mirrored and magnified in the events that shape the newborn nation of India. It is a great gift, and a terrible burden. ", NumberOfPages = 672, DatePublished = new DateModel(2008, 07, 14), Publisher = "Vintage Publishing", Rating = 4.0, NumberOfRatings = 15, NumberOfCopiesSold = 18, InStock = 12, Genre="Fantasy", Price = 12.99},
                    new BookEntityModel { Title = "Lolita", Author = "Vladimir Nabokov", ISBN10 = "0241953243", ISBN13 = "9780241953242", Description = "Vladimir Nabokov's Lolita is one of the best-known novels of the 20th century: the controversial story of Humbert Humbert who falls in love with twelve year old Lolita, beautifully repackaged as part of the Penguin Essentials range. Humbert Humbert is a middle-aged, frustrated college professor. In love with his landlady's twelve-year-old daughter Lolita, he'll do anything to possess her. Unable and unwilling to stop himself, he is prepared to commit any crime to get what he wants.  ", NumberOfPages = 268, DatePublished = new DateModel(2011, 09, 01), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 14, NumberOfCopiesSold = 19, InStock = 7, Genre="Fantasy", Price = 9.99},
                    new BookEntityModel { Title = "The Secret History", Author = "Donna Tartt", ISBN10 = "0140167773", ISBN13 = "9780140167771", Description = "Under the influence of their charismatic classics professor, a group of clever, eccentric misfits at an elite New England college discover a way of thinking and living that is a world away from the humdrum existence of their contemporaries. But when they go beyond the boundaries of normal morality their lives are changed profoundly and for ever. ", NumberOfPages = 640, DatePublished = new DateModel(1995, 09, 01), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 94, NumberOfCopiesSold = 120, InStock = 2, Genre="Fantasy", Price = 11.99},
                    new BookEntityModel { Title = "The Remains of the Day", Author = "Kazuo Ishiguro", ISBN10 = "0571258247", ISBN13 = "9780571258246", Description = "A contemporary classic, The Remains of the Day is Kazuo Ishiguro's beautiful and haunting evocation of life between the wars in a Great English House. ", NumberOfPages = 272, DatePublished = new DateModel(2010, 04, 01), Publisher = "FABER & FABER", Rating = 4.0, NumberOfRatings = 19, NumberOfCopiesSold = 39, InStock = 17, Genre="Romance", Price = 8.99},
                    new BookEntityModel { Title = "A Fine Balance", Author = "Rohinton Mistry", ISBN10 = "057123058X", ISBN13 = "9780571230587", Description = "Set in mid-1970s India, A Fine Balance is a subtle and compelling narrative about four unlikely characters who come together in circumstances no one could have foreseen soon after the government declares a 'State of Internal Emergency'. It is a breathtaking achievement: panoramic yet humane, intensely political yet rich with local delight; and, above all, compulsively readable. ", NumberOfPages = 624, DatePublished = new DateModel(2006, 10, 19), Publisher = "FABER & FABER", Rating = 4.0, NumberOfRatings = 23, NumberOfCopiesSold = 50, InStock = 38, Genre="fantasy", Price = 10.99},
                    new BookEntityModel { Title = "Heart of Darkness", Author = "Joseph Conrad", ISBN10 = "0141441674", ISBN13 = "9780141441672", Description = "A haunting and hugely influential Modernist masterpiece, the Penguin Classics edition of Joseph Conrad's Heart of Darkness is edited with an introduction by Owen Knowles. Conrad's narrator Marlow, a seaman and wanderer, recounts his physical and psychological journey in search of the infamous ivory trader Kurtz: dying, insane, and guilty of unspeakable atrocities. Travelling upriver to the heart of the African continent, he gradually becomes obsessed by this enigmatic, wraith-like figure. Marlow's discovery of how Kurtz has gained his position of power over the local people involves him in a radical questioning, not only of his own nature and values, but also those of western civilisation. The inspiration for Francis Ford Coppola's Oscar-winning film Apocalypse Now, Heart of Darkness is a quintessentially modernist work exploring the limits of human experience and the nightmarish realities of imperialism. Part of a major series of new editions of Conrad's most famous works in Penguin Classics, this volume contains Conrad's Congo Diary, a chronology, further reading, notes, a map of the Congo, a glossary and an introduction discussing the author's experiences in Africa, the narrative and symbolic complexities of Heart of Darkness and critical responses to the novel. Joseph Conrad (1857-1924) was born in the Ukraine and grew up under Tsarist autocracy. After spending years in the French, and later the British Merchant Navy, Conrad left the sea to devote himself to writing. In 1896 he settled in Kent, where he produced within fifteen years such modern classics as Youth, Heart of Darkness, Lord...show more", NumberOfPages = 192, DatePublished = new DateModel(2007, 12, 01), Publisher = "Penguin Books Ltd", Rating = 3.5, NumberOfRatings = 42, NumberOfCopiesSold = 32, InStock = 31, Genre="Fantsy", Price =6.99},
                    new BookEntityModel { Title = "A Confederacy of Dunces", Author = "John Kennedy Toole", ISBN10 = "0241951593", ISBN13 = "9780241951590", Description = "Meet the fat, flatulent and eloquent Ignatius J. Reilly in John Kennedy Toole's light and pithy comic tale A Confederacy of Dunces, beautifully repackaged as part of the Penguin Essentials range. 'This city is famous for its gamblers, prostitutes, exhibitionists, anti-Christs, alcoholics, sodomites, drug addicts, fetishists, onanists, pornographers, frauds, jades, litterbugs, and lesbians . . . don't make the mistake of bothering me.' Ignatius J. Reilly: fat, flatulent, eloquent and almost unemployable. By the standards of ordinary folk he is pretty much unhinged, too. But is he bothered by this? No. For this misanthropic crusader against an America fallen into vice and ignorance has a mission: to rescue a naked female philosopher in distress. And he has a pirate costume and hot-dog cart to do it with . . .", NumberOfPages = 416, DatePublished = new DateModel(2011, 07, 04), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 18, NumberOfCopiesSold = 12, InStock = 8, Genre="fantasy", Price = 7.99},
                    new BookEntityModel { Title = "Les Miserables", Author = "Victor Hugo", ISBN10 = "0140444300", ISBN13 = "9780140444308", Description = "Now a major musical film from Oscar-winning director Tom Hooper (The King's Speech), starring Hugh Jackman, Russell Crowe and Anne Hathaway, and also featuring Amanda Seyfreid, Helena Bonham-Carter and Sacha Baron-Cohen, Victor Hugo's Les Miserables is one of the great works of western literature. Now in a new translation from the French by Christine Donougher, Les Miserables is at once a thrilling narrative - part comedy, mystery, romance and tragedy - and a social document of France's turbulent revolutionary history. Victor Hugo's tale of injustice, heroism and love follows the fortunes of Jean Valjean (Hugh Jackman), an escaped convict determined to put his criminal past behind him. But his attempts to become a respected member of the community are constantly put under threat: by his own conscience, when, owing to a case of mistaken identity, another man is arrested in his place; and by the relentless investigations of the dogged Inspector Javert (Russell Crowe). It is not simply for himself that Valjean must stay free, however, for he has sworn to protect the baby daughter of Fantine (Anne Hathaway), driven to prostitution by poverty. show more", NumberOfPages = 1232, DatePublished = new DateModel(1982, 06, 01), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 42, NumberOfCopiesSold = 120, InStock = 14, Genre="Fantasy", Price = 14.99},
                    new BookEntityModel { Title = "Lost Illusions", Author = "Honore de Balzac", ISBN10 = "0140442510", ISBN13 = "9780140442519", Description = "Handsome would-be poet Lucien Chardon is poor and naive, but highly ambitious. Failing to make his name in his dull provincial hometown, he is taken up by a patroness, the captivating married woman Madame de Bargeton, and prepares to forge his way in the glamorous beau monde of Paris. But Lucien has entered a world far more dangerous than he realized, as Madame de Bargeton's reputation becomes compromised and the fickle, venomous denizens of the courts and salons conspire to keep him out of their ranks. Lucien eventually learns that, wherever he goes, talent counts for nothing in comparison to money, intrigue and unscrupulousness. Lost Illusions is one of the greatest novels in the rich procession of the Comedie humaine, Balzac's panoramic social and moral history of his times. ", NumberOfPages = 720, DatePublished = new DateModel(2000, 01, 21), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings =38 , NumberOfCopiesSold = 114, InStock = 17, Genre="", Price = .99},
                    new BookEntityModel { Title = "The Red and the Black", Author = "Stendhal", ISBN10 = "0140447644", ISBN13 = "9780140447644", Description = "Charting the rise and fall of an ambitious young social climber in a cruel, monarchical society, Stendhal's The Red and the Black is translated with an introduction and notes by Roger Gard in Penguin Classics. Handsome, ambitious Julien Sorel is determined to rise above his humble provincial origins. Soon realizing that success can only be achieved by adopting the subtle code of hypocrisy by which society operates, he begins to achieve advancement through deceit and self-interest. His triumphant career takes him into the heart of glamorous Parisian society, along the way conquering the gentle, married Madame de Renal, and the haughty Mathilde. But then Julien commits an unexpected, devastating crime - and brings about his own downfall. The Red and the Black is a lively, satirical portrayal of French society after Waterloo, riddled with corruption, greed and ennui, and Julien - the cold exploiter whose Machiavellian campaign is undercut by his own emotions - is one of the most intriguing characters in European literature.", NumberOfPages = 608, DatePublished = new DateModel(2002, 10, 01), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 17, NumberOfCopiesSold = 18, InStock = 8, Genre="Adventure", Price = 10.99},
                    new BookEntityModel { Title = "Stories", Author = "Anton Chekhov", ISBN10 = "0553381008", ISBN13 = "9780553381009", Description = "Richard Pevear and Larissa Volokhonsky, the highly acclaimed translators of War and Peace, Doctor Zhivago, and Anna Karenina, which was an Oprah Book Club pick and million-copy bestseller, bring their unmatched talents to The Selected Stories of Anton Chekhov, a collection of thirty of Chekhov's best tales from the major periods of his creative life. Considered the greatest short story writer, Anton Chekhov changed the genre itself with his spare, impressionistic depictions of Russian life and the human condition. From characteristically brief, evocative early pieces such as 'The Huntsman' and the tour de force 'A Boring Story,' to his best-known stories such as 'The Lady with the Little Dog' and his own personal favorite, 'The Student,' Chekhov's short fiction possesses the transcendent power of art to awe and change the reader. This monumental edition, expertly translated, is especially faithful to the meaning of Chekhov's prose and the unique rhythms of his writing, giving readers an authentic sense of his style and a true understanding of his greatness.", NumberOfPages = 496, DatePublished = new DateModel(2000, 11, 01), Publisher = "Bantam Doubleday Dell Publishing Group Inc", Rating = 4.0, NumberOfRatings = 17, NumberOfCopiesSold = 120, InStock = 8, Genre="", Price = 9.99},
                    new BookEntityModel { Title = "The Idiot", Author = "Fyodor Dostoyevsky", ISBN10 = "014044792X", ISBN13 = "9780140447927", Description = "Fyodor Dostoyevsky's The Idiot is an immaculate portrait of innocence tainted by the brutal reality of human greed. This Penguin Classics edition is translated from the Russian by David McDuff, with an introduction by William Mills Todd III. Returning to St Petersburg from a Swiss sanatorium, the gentle and naive epileptic Prince Myshkin - the titular 'idiot' - pays a visit to his distant relative General Yepanchin and proceeds to charm the General, his wife, and his three daughters. But his life is thrown into turmoil when he chances on a photograph of the beautiful Nastasya Filippovna. Utterly infatuated with her, he soon finds himself caught up in a love triangle and drawn into a web of blackmail, betrayal, and finally, murder. Inspired by an image of Christ's suffering Dostoyevsky sought to portray in Prince Myshkin the purity of a 'truly beautiful soul' and explore the perils that innocence and goodness face in a corrupt world. David McDuff's new translation brilliantly captures the novel's idiosyncratic and dream-like language and the nervous, elliptic flow of the narrative. This edition also contains a new introduction by William Mills Todd III, which is a fascinating examination of the pressures on Dostoyevsky as he wrote the story of his Christ-like hero... ", NumberOfPages = 784, DatePublished = new DateModel(2015, 09, 01), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 17, NumberOfCopiesSold = 29, InStock = 8, Genre="Fantasy", Price = 11.99},
                    new BookEntityModel { Title = "Republic", Author = "Plato", ISBN10 = "0199535760", ISBN13 = "9780199535767", Description = "Republic is the central work of the Western world's most famous philosopher. Essentially an inquiry into morality, Republic also contains crucial arguments and insights into many other areas of philosophy. It is also a literary masterpiece: the philosophy is presented for the most part for the ordinary reader, who is carried along by the wit and intensity of the dialogue and by Plato's unforgettable images of the human condition. This new, lucid translation by Robin Waterfield is complemented by full explanatory notes and an up-to-date critical introduction. ABOUT THE SERIES: For over 100 years Oxford World's Classics has made available the widest range of literature from around the globe. Each affordable volume reflects Oxford's commitment to scholarship, providing the most accurate text plus a wealth of other valuable features, including expert introductions by leading authorities, helpful notes to clarify the text, up-to-date bibliographies for further study, and much more. ", NumberOfPages = 560, DatePublished = new DateModel(2008, 06, 01), Publisher = "Oxford University Press", Rating = 4.0, NumberOfRatings = 7, NumberOfCopiesSold = 12, InStock = 48, Genre="Learning", Price = 8.99},
                    new BookEntityModel { Title = "Walden", Author = "Henry David Thoreau ", ISBN10 = "0300104669", ISBN13 = "9780300104660", Description = "This is the authoritative edition of an American literaru classic: Henry David Thoreau's Walden, an elegantly written record of his experiment in simple living. With this edition, Thoreau scholar Jeffrey S. Cramer has meticulously corrected errors and omissions from previous editions of Walden and here provides illuminating notes on the biographical, historical, and geographical contexts of the great nineteenth-century writer and thinker's life. Cramer's newly edited text is based on the original 1854 edition of Walden, with emendations taken from Thoreau's draft manuscripts, his own markings on the page proofs, and notes in his personal copy of the book. In the editor's notes to the volume, Cramer quotes from sources Thoreau actually read, showing how he used, interpreted, and altered these sources. Cramer also glosses Walden with references to Thoreau's essays, journals, and correspondence. With the wealth of material in this edition, readers will find an unprecedented opportunity to immerse themselves in the unique and fascinating world of Thoreau. Anyone who has read and loved Walden will want to own and treasure this gift edition. ", NumberOfPages = 400, DatePublished = new DateModel(2004, 06, 11), Publisher = "New Haven, United States", Rating = 4.0, NumberOfRatings = 11, NumberOfCopiesSold = 27, InStock = 17, Genre="Learning", Price = 26.99},
                    new BookEntityModel { Title = "The Stranger", Author = "Albert Camus", ISBN10 = "0679720200", ISBN13 = "9780679720201", Description = "Through the story of an ordinary man unwittingly drawn into a senseless murder on an Algerian beach, Camus explored what he termed -the nakedness of man faced with the absurd.- First published in 1946; now in a new translation by Matthew Ward. ", NumberOfPages = 144, DatePublished = new DateModel(1992, 12, 01), Publisher = "Random House USA Inc", Rating = 4.0, NumberOfRatings = 2, NumberOfCopiesSold = 5, InStock = 10, Genre="Fantasy", Price = 9.99},
                    new BookEntityModel { Title = "A Portrait of the Artist as a Young Man", Author = "James Joyce", ISBN10 = "0141182660", ISBN13 = "9780141182667", Description = "The portrayal of Stephen Dedalus's Dublin childhood and youth, his quest for identity through art and his gradual emancipation from the claims of family, religion and Ireland itself, is also an oblique self-portrait of the young James Joyce and a universal testament to the artist's 'eternal imagination'. Both an insight into Joyce's life and childhood, and a unique work of modernist fiction, A Portrait of the Artist as a Young Man is a novel of sexual awakening, religious rebellion and the essential search for voice and meaning that every nascent artist must face in order to fully come into themselves.", NumberOfPages = 384, DatePublished = new DateModel(2000, 02, 24), Publisher = "Penguin Books Ltd", Rating = 3.5, NumberOfRatings = 9, NumberOfCopiesSold = 12, InStock = 18, Genre="Fantasy", Price = 8.99},
                    new BookEntityModel { Title = "The Unconscious", Author = "Sigmund Freud", ISBN10 = "0141183888", ISBN13 = "9780141183886", Description = "One of Freud's central achievements was to demonstrate how unacceptable thoughts and feelings are repressed into the unconscious, from where they continue to exert a decisive influence over our lives. This volume contains a key statement about evidence for the unconscious, and how it works, as well as major essays on all the fundamentals of mental functioning. Freud explores how we are torn between the pleasure principle and the reality principle, how we often find ways both to express and to deny what we most fear, and why certain men need fetishes for their sexual satisfaction. His study of our most basic drives, and how they are transformed, brilliantly illuminates the nature of sadism, masochism, exhibitionism and voyeurism. ", NumberOfPages = 144, DatePublished = new DateModel(2015, 10, 06), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 267, NumberOfCopiesSold = 324, InStock = 120, Genre="Learning", Price = 9.99},
                    new BookEntityModel { Title = "Grundrisse", Author = "Karl Marx", ISBN10 = "0140445757", ISBN13 = "9780140445756", Description = "Written during the winter of 1857-8, the Grundrisse was considered by Marx to be the first scientific elaboration of communist theory. A collection of seven notebooks on capital and money, it both develops the arguments outlined in the Communist Manifesto (1848) and explores the themes and theses that were to dominate his great later work Capital. Here, for the first time, Marx set out his own version of Hegel's dialectics and developed his mature views on labour, surplus value and profit, offering many fresh insights into alienation, automation and the dangers of capitalist society. Yet while the theories in Grundrisse make it a vital precursor to Capital, it also provides invaluable descriptions of Marx's wider-ranging philosophy, making it a unique insight into his beliefs and hopes for the foundation of a communist state. ", NumberOfPages = 912, DatePublished = new DateModel(1992, 09, 07), Publisher = "Penguin Books Ltd", Rating = 2.0, NumberOfRatings = 118, NumberOfCopiesSold = 144, InStock = 112, Genre="Learning", Price = 19.99},
                    new BookEntityModel { Title = "The Prince", Author = "Niccolo Machiavelli", ISBN10 = "0199535698", ISBN13 = "9780199535699", Description = "'A prince must not have any other object nor any other thought...but war, its institutions, and its discipline; because that is the only art befitting one who commands.' When Machiavelli's brief treatise on Renaissance statecraft and princely power was posthumously published in 1532, it generated a debate that has raged unabated until the present day. Based upon Machiavelli's first-hand experience as an emissary of the Florentine Republic to the courts of Europe, The Prince analyses the usually violent means by which men seize, retain, and lose political power. Machiavelli added a dimension of incisive realism to one of the major philosophical and political issues of his time, especially the relationship between public deeds and private morality. His book provides a remarkably uncompromising picture of the true nature of power, no matter in what era or by whom it is exercised. This fluent new translation is accompanied by comprehensive notes and an introduction that considers the true purpose of The Prince and dispels some of the myths associated with it.", NumberOfPages = 192, DatePublished = new DateModel(2008, 06, 01), Publisher = "Oxford University Press", Rating = 4.0, NumberOfRatings = 17, NumberOfCopiesSold = 30, InStock = 8, Genre="", Price = 6.99},
                    new BookEntityModel { Title = "Moby Dick", Author = "Herman Melville", ISBN10 = "0199535728", ISBN13 = "9780199535729", Description = "This classic story of high adventure, manic obsession, and metaphysical speculation was Melville's masterpiece. The tale of Captain Ahab's frantic pursuit of the cunning and notorious white whale Moby Dick, is packed with drama, and draws heavily on the author's own experiences on the high seas. This edition includes passages from Melville's correspondence with Nathaniel Hawthorne, in which the two discussed the philosophical depths of the novel's plot and imagery. ABOUT THE SERIES: For over 100 years Oxford World's Classics has made available the widest range of literature from around the globe. Each affordable volume reflects Oxford's commitment to scholarship, providing the most accurate text plus a wealth of other valuable features, including expert introductions by leading authorities, helpful notes to clarify the text, up-to-date bibliographies for further study, and much more. ", NumberOfPages = 592, DatePublished = new DateModel(2008, 09, 01), Publisher = "Oxford University Press", Rating = 4.0, NumberOfRatings = 65, NumberOfCopiesSold = 173, InStock = 6, Genre="Adventure", Price = 8.99},
                };

                db.AddRange(initialBooks);
                db.SaveChanges();
            }
        }
    }
}
