using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TheBookCave.Data;
using TheBookCave.Data.EntityModels;
using TheBookCave.Models;

namespace TheBookCave
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = BuildWebHost(args);
            SeedData();
            host.Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();

        public static void SeedData()
        {
            var db = new DataContext();

            if(!db.Books.Any())
            {
                var initialBooks = new List<BookEntityModel>()
                {
                    new BookEntityModel { Title = "The Art of War", Author = "Sun Tzu", ISBN10 = "0141023813", ISBN13 = "9780141023816", Description = "Throughout history, some books have changed the world. They have transformed the way we see ourselves and each other. They have inspired debate, dissent, war and revolution. They have enlightened, outraged, provoked and comforted. They have enriched lives and destroyed them. Now Penguin brings you the works of the great thinkers, pioneers, radicals and visionaries whose ideas shook civilization and helped make us who we are. Offering ancient wisdom on how to use skill, cunning, tactics and discipline to outwit your opponent, this bestselling 2000-year-old military manual is still worshipped by soldiers on the battlefield and managers in the boardroom as the ultimate guide to winning. ", NumberOfPages = 112, DatePublished = new DateModel(2005, 08, 25), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 11, NumberOfCopiesSold = 6, InStock = 214, Genre="Learning", Price = 5.99},
                    new BookEntityModel { Title = "The Fault In Our Stars", Author = "John Green", ISBN10 = "0525426000", ISBN13 = "9780525426004", Description = "'The greatest romance story of this decade.' —Entertainment Weekly", NumberOfPages = 324, DatePublished = new DateModel(2013, 01, 23), Publisher = "Penguin Putnam Inc", Rating = 4.5, NumberOfRatings = 122, NumberOfCopiesSold = 220, InStock = 170, Genre="", Price = 9.99},
                    new BookEntityModel { Title = "Man & His Symbols", Author = "Carl Gustav Jung", ISBN10 = "0440351839", ISBN13 = "9780440351832", Description = "Illustrated throughout with revealing images, this is the first and only work in which the world-famous Swiss psychologist explains to the layperson his enormously influential theory of symbolism as revealed in dreams. ", NumberOfPages = 432, DatePublished = new DateModel(1999, 03, 31), Publisher = "Bantam Doubleday Dell Publishing Group Inc", Rating = 4.0, NumberOfRatings = 13, NumberOfCopiesSold = 120, InStock = 8, Genre="Educational", Price = 7.99},
                    new BookEntityModel { Title = "Candide, or Optimism", Author = "Voltaire", ISBN10 = "0140455108", ISBN13 = "9780140455106", Description = "Voltaire's brilliant satirical assault on what he saw as the naively optimistic philosophy of the Enlightenment, Candide, or Optimism is a dazzling picaresque novel, translated and edited by Theo Cuffe with an introduction by Michael Wood in Penguin Classics. Brought up in the household of a German Baron, Candide is an open-minded young man whose tutor, Pangloss, has instilled in him the belief, inspired by Leibniz, that 'all is for the best in this, the best of all possible worlds'. But when his love for the Baron's rosy-cheeked daughter is discovered, Candide is cast out to make his own fortune. As he and his various companions roam over the world, an outrageous series of disasters befall them - earthquakes, syphilis, a brush with the Inquisition, murder - sorely testing the young hero's optimism. In Candide, Voltaire threw down an audacious challenge to the philosophical views of his time, to create one of the most glorious satires of the eighteenth century.", NumberOfPages = 208, DatePublished = new DateModel(2000, 01, 21), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 32, NumberOfCopiesSold = 137, InStock = 44, Genre="Fantasy", Price = 6.99},
                    new BookEntityModel { Title = "On the Origin of Species", Author = "Charles Darwin", ISBN10 = "0199219222", ISBN13 = "9780199219223", Description = "'can we doubt ...that individuals having any advantage, however slight, over others, would have the best chance of surviving and of procreating their kind?' In the Origin of Species (1859) Darwin challenged many of the most deeply held beliefs of the Western world. His insistence on the immense length of the past and on the abundance of life-forms, present and extinct, dislodged man from his central position in creation and called into question the role of the Creator. He showed that new species are achieved by natural selection, and that absence of plan is an inherent part of the evolutionary process. Darwin's prodigious reading, experimentation, and observations on his travels fed into his great work, which draws on material from the Galapagos Islands to rural Staffordshire, from English back gardens to colonial encounters. The present edition provides a detailed and accessible discussion of his theories and adds an account of the immediate responses to the book on publication. The resistances as well as the enthusiasms of the first readers cast light on recent controversies, particularly concerning questions of design and descent. ABOUT THE SERIES: For over 100 years Oxford World's Classics has made available the widest range of literature from around the globe. Each affordable volume reflects Oxford's commitment to scholarship, providing the most accurate text plus a wealth of other valuable features, including expert introductions by leading authorities, helpful notes to clarify the text, up-to-date bibliographies for further study, and much more. ", NumberOfPages = 432, DatePublished = new DateModel(2009, 02, 01), Publisher = "Oxford University Press", Rating = 4.0, NumberOfRatings = 43, NumberOfCopiesSold = 76, InStock = 22, Genre="Educational", Price = 8.99},
                    new BookEntityModel { Title = "The Path To Power", Author = "Robert A. Caro", ISBN10 = "0712698795", ISBN13 = "9780712698795", Description = "This is the story of the rise to national power of a desperately poor young man from the Texas Hill Country, and the first volume in Robert Caro's The Years of Lyndon Johnson, hailed as `the greatest biography of our era'. ", NumberOfPages = 912, DatePublished = new DateModel(1992, 11, 12), Publisher = "Vintage Publishing", Rating = 4.5, NumberOfRatings = 98, NumberOfCopiesSold = 150, InStock = 47, Genre="Biography", Price = 28.99},
                    new BookEntityModel { Title = "Faust: Part One", Author = "J. W. Von Goethe", ISBN10 = "019953621X", ISBN13 = "9780199536214", Description = "The legend of Faust grew up in the sixteenth century, a time of transition between medieval and modern culture in Germany. Johann Wolfgang von Goethe (1749-1832) adopted the story of the wandering conjuror who accepts Mephistopheles's offer of a pact, selling his soul for the devil's greater knowledge; over a period of 60 years he produced one of the greatest dramatic and poetic masterpieces of European literature. David Luke's recent translation, specially commissioned for The World's Classics series, has all the virtues of previous classic translations of Faust, and none of their shortcomings. Cast in rhymed verse, following the original, it preserves the essence of Goethe's meaning without sacrifice to archaism or over-modern idiom. It is as near an 'equivalent' rendering of the German as has been achieved. ABOUT THE SERIES: For over 100 years Oxford World's Classics has made available the widest range of literature from around the globe. ", NumberOfPages = 240, DatePublished = new DateModel(2008, 07, 15), Publisher = "Oxford University Press", Rating = 4.0, NumberOfRatings = 17, NumberOfCopiesSold = 40, InStock = 27, Genre="Fantasy", Price = 7.99},
                    new BookEntityModel { Title = "One Flew Over the Cuckoo's Nest", Author = "Ken Kesey", ISBN10 = "0141187883", ISBN13 = "9780141187884", Description = "Pitching an extraordinary battle between cruel authority and a rebellious free spirit, Ken Kesey's One Flew Over the Cuckoo's Nest is a novel that epitomises the spirit of the sixties. This Penguin Classics edition includes a preface, never-before published illustrations by the author, and an introduction by Robert Faggen. Tyrannical Nurse Ratched rules her ward in an Oregon State mental hospital with a strict and unbending routine, unopposed by her patients, who remain cowed by mind-numbing medication and the threat of electroshock therapy. But her regime is disrupted by the arrival of McMurphy - the swaggering, fun-loving trickster with a devilish grin who resolves to oppose her rules on behalf of his fellow inmates. His struggle is seen through the eyes of Chief Bromden, a seemingly mute half-Indian patient who understands McMurphy's heroic attempt to do battle with the powers that keep them imprisoned. The subject of an Oscar-winning film starring Jack Nicholson, One Flew Over the Cuckoo's Nest an exuberant, ribald and devastatingly honest portrayal of the boundaries between sanity and madness.", NumberOfPages = 320, DatePublished = new DateModel(2011, 06, 17), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 15, NumberOfCopiesSold = 18, InStock = 8, Genre="Fantasy", Price = 8.99},
                    new BookEntityModel { Title = "Beloved", Author = "Toni Morrison", ISBN10 = "0099511657", ISBN13 = "9780099511656", Description = "Terrible, unspeakable things happened to Sethe at Sweet Home, the farm where she lived as a slave for so many years until she escaped to Ohio. Her new life is full of hope but eighteen years later she is still not free. Sethe's new home is not only haunted by the memories of her past but also by the ghost of her baby, who died nameless and whose tombstone is engraved with a single word: Beloved. ", NumberOfPages = 352, DatePublished = new DateModel(2011, 03, 28), Publisher = "Vintage Publishing", Rating = 4.0, NumberOfRatings = 17, NumberOfCopiesSold = 29, InStock = 14, Genre="Fantasy", Price = 8.99},
                    new BookEntityModel { Title = "Another Country", Author = "James Baldwin", ISBN10 = "0141186372", ISBN13 = "9780141186375", Description = "When Another Country appeared in 1962, it caused a literary sensation. James Baldwin's masterly story of desire, hatred and violence opens with the unforgettable character of Rufus Scott, a scavenging Harlem jazz musician adrift in New York. Self-destructive, bad and brilliant, he draws us into a Bohemian underworld pulsing with heat, music and sex, where desperate and dangerous characters betray, love and test each other to the limit. ", NumberOfPages = 448, DatePublished = new DateModel(2010, 05, 01), Publisher = "Penguin Books Ltd", Rating = 4.5, NumberOfRatings = 23, NumberOfCopiesSold = 60, InStock = 12, Genre="Fantasy", Price = 10.99},
                    new BookEntityModel { Title = "I Know Why the Caged Bird Sings", Author = "Maya Angelou", ISBN10 = "0345514408", ISBN13 = "9780345514400", Description = "Sent by their mother to live with their devout, self-sufficient grandmother in a small Southern town, Maya and her brother, Bailey, endure the ache of abandonment and the prejudice of the local `powhitetrash.` At eight years old and back at her mother's side in St. Louis, Maya is attacked by a man many times her age-and has to live with the consequences for a lifetime. Years later, in San Francisco, Maya learns about love for herself and the kindness of others, her own strong spirit, and the ideas of great authors (`I met and fell in love with William Shakespeare`) will allow her to be free instead of imprisoned. ", NumberOfPages = 289, DatePublished = new DateModel(2009, 04, 21), Publisher = "Random House USA Inc", Rating = 4.0, NumberOfRatings = 15, NumberOfCopiesSold = 19, InStock = 24, Genre="Biography", Price = 6.99},
                    new BookEntityModel { Title = "The Good Soldier Svejk", Author = "Jaroslav Hasek", ISBN10 = "0140449914", ISBN13 = "9780140449914", Description = "Good-natured and garrulous, Svejk becomes the Austro-Hungarian army's most loyal Czech soldier when he is called up on the outbreak of the First World War - although his bumbling attempts to get to the front serve only to prevent him from reaching it. Playing cards, getting drunk and becoming a general nuisance, the resourceful Svejk uses all his natural cunning and genial subterfuge to deal with the doctors, police, clergy and officers who chivvy him towards battle. The story of a 'little man' caught in a vast bureaucratic machine, The Good Soldier Svejk combines dazzling wordplay and piercing satire to create a hilariously subversive depiction of the futility of war.", NumberOfPages = 784, DatePublished = new DateModel(2005, 12, 27), Publisher = "Penguin Books Ltd", Rating = 5.0, NumberOfRatings = 120, NumberOfCopiesSold = 216, InStock = 32, Genre="Fantasy", Price = 13.99},
                    new BookEntityModel { Title = "Metamorphosis and Other Stories", Author = "Franz Kafka", ISBN10 = "0749399538", ISBN13 = "9780749399535", Description = "WITH AN INTRODUCTION BY ADAM THIRLWELL One morning, Gregor Samsa wakes up to find himself transformed into a giant insect. His family is understandably perturbed and he finds himself an outsider in his own home. In 'Metamorphosis' and the other famous stories included here, Kafka explores the confusing nature of human experience with sly wit and compelling originality. ", NumberOfPages = 240, DatePublished = new DateModel(1992, 01, 23), Publisher = "Vintage Publishing", Rating = 4.0, NumberOfRatings = 17, NumberOfCopiesSold = 43, InStock = 16, Genre="Fiction", Price = 10.99},
                    new BookEntityModel { Title = "Watt", Author = "Samuel Beckett", ISBN10 = "0571244742", ISBN13 = "9780571244744", Description = "Written in Roussillon during World War Two, while Samuel Beckett was hiding from the Gestapo, Watt was first published in 1953. Beckett acknowledged that this comic novel unlike any other 'has its place in the series' - those masterpieces running from Murphy to the Trilogy, Waiting for Godot and beyond. It shares their sense of a world in crisis, their profound awareness of the paradoxes of being, and their distrust of the rational universe. Watt tells the tale of Mr Knott's servant and his attempts to get to know his master. Watt's mistake is to derive the essence of his master from the accidentals of his being, and his painstakingly logical attempts to 'know' ultimately consign him to the asylum. Itself a critique of error, Watt has previously appeared in editions that are littered with mistakes, both major and minor. The new Faber edition offers for the first time a corrected text based on a scholarly appraisal of the manuscripts and textual history. ", NumberOfPages = 272, DatePublished = new DateModel(2009, 05, 21), Publisher = "FABER & FABER", Rating = 4.0, NumberOfRatings = 23, NumberOfCopiesSold = 42, InStock = 72, Genre="War", Price = 10.99},
                    new BookEntityModel { Title = "The Call of the Wild", Author = "Jack London", ISBN10 = "0141321059", ISBN13 = "9780141321059", Description = "Life is good for Buck in Santa Clara Valley, where he spends his days eating and sleeping in the golden sunshine. But one day a treacherous act of betrayal leads to his kidnap, and he is forced into a life of toil and danger. Dragged away to be a sledge dog in the harsh and freezing cold Yukon, Buck must fight for his survivial. Can he rise above his enemies and become the master of his realm once again? ", NumberOfPages = 160, DatePublished = new DateModel(2008, 04, 01), Publisher = "", Rating = 4.5, NumberOfRatings = 73, NumberOfCopiesSold = 420, InStock = 17, Genre="Children", Price = 4.99},
                    new BookEntityModel { Title = "Ethics", Author = "Benedict de Spinoza", ISBN10 = "0140435719", ISBN13 = "9780140435719", Description = "A profoundly beautiful and uniquely insightful description of the universe, Benedict de Spinoza's Ethics is one of the masterpieces of Enlightenment-era philosophy. This Penguin Classics edition is edited and translated from the Latin by Edwin Curley, with an introduction by Stuart Hampshire. Published shortly after his death, the Ethics is undoubtedly Spinoza's greatest work - an elegant, fully cohesive cosmology derived from first principles, providing a coherent picture of reality, and a guide to the meaning of an ethical life. Following a logical step-by-step format, it defines in turn the nature of God, the mind, the emotions, human bondage to the emotions, and the power of understanding - moving from a consideration of the eternal, to speculate upon humanity's place in the natural order, the nature of freedom and the path to attainable happiness. A powerful work of elegant simplicity, the Ethics is a brilliantly insightful consideration of the possibility of redemption through intense thought and philosophical reflection.", NumberOfPages = 208, DatePublished = new DateModel(2005, 07, 26), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 13, NumberOfCopiesSold = 120, InStock = 8, Genre="Educational", Price = 9.99},
                    new BookEntityModel { Title = "Leviathan", Author = "Thomas Hobbes", ISBN10 = "0199537283", ISBN13 = "9780199537280", Description = "He that is to govern a whole nation, must read in himself, not this, or that particular man; but mankind. Leviathan is both a magnificent literary achievement and the greatest work of political philosophy in the English language. Permanently challenging, it has found new applications and new refutations in every generation. Hobbes argues that human beings are first and foremost concerned with their own individual desires and fears. He shows that a conflict of each against every man can only be avoided by the adoption of a compact to enforce peace. The compact involves giving up some of our natural freedom to a sovereign power which will enforce the laws of peace on all citizens. Hobbes also analyses the subversive forces - religion, ambition, private conscience - that threaten to destroy the body politic, Leviathan itself, and return us to the state of war. This new edition reproduces the first printed text, retaining the original punctuation but modernizing the spelling. It offers exceptionally thorough and useful annotation, an introduction that guides the reader through the complexities of Hobbes's arguments, and a substantial index. ", NumberOfPages = 576, DatePublished = new DateModel(2009, 12, 01), Publisher = "Oxford University Press", Rating = 4.5, NumberOfRatings = 3, NumberOfCopiesSold = 12, InStock = 80, Genre="Educational", Price = 9.99},
                    new BookEntityModel { Title = "Robinson Crusoe", Author = "Daniel Defoe", ISBN10 = "0199553971", ISBN13 = "9780199553976", Description = "'I made him know his Name should be Friday, which was the Day I sav'd his Life...I likewise taught him to say Master' Robinson Crusoe's seafaring adventures are abruptly ended when he is shipwrecked, the solitary survivor on a deserted island. He gradually creates a life for himself, building a house, cultivating the land, and making a companion from the native whose life he saves. Daniel Defoe's enthralling story-telling and imaginatively detailed descriptions have ensured that his fiction masquerading as fact remains one of the most famous stories in English literature. On one level a simple adventure story, the novel also raises profound questions about moral and spiritual values, society, and man's abiding acquisitiveness. This new edition includes a scintillating Introduction and notes that illuminate the historical context. ABOUT THE SERIES: For over 100 years Oxford World's Classics has made available the widest range of literature from around the globe. ", NumberOfPages = 384, DatePublished = new DateModel(2009, 04, 15), Publisher = "Oxford University Press", Rating = 3.5, NumberOfRatings = 43, NumberOfCopiesSold = 50, InStock = 34, Genre="Fiction", Price = 14.99},
                    new BookEntityModel { Title = "I, Claudius", Author = "Robert Graves", ISBN10 = "0141188596", ISBN13 = "9780141188591", Description = "Bringing to life the subterfuge and double-dealing of Roman nobility, Robert Graves's I, Claudius brings the ancient world to life with startling clarity and meticulous realism. This Penguin Modern Classics edition is a includes an introduction by Barry Unsworth. Despised for his weakness and regarded by his family as little more than a stammering fool, the nobleman Claudius quietly survives the intrigues, bloody purges and mounting cruelty of the imperial Roman dynasties. In I, Claudius he watches from the sidelines to record the reigns of its emperors: from the wise Augustus and his villainous wife Livia to the sadistic Tiberius and the insane excesses of Caligula. Written in the form of Claudius' autobiography, this is the first part of Robert Graves's brilliant account of the madness and debauchery of ancient Rome, and stands as one of the most celebrated, gripping historical novels ever written.", NumberOfPages = 416, DatePublished = new DateModel(2015, 08, 03), Publisher = "Penguin Books Ltd", Rating = 5.0, NumberOfRatings = 7, NumberOfCopiesSold = 10, InStock = 20, Genre="Fiction", Price = 9.99},
                    new BookEntityModel { Title = "Portnoy's Complaint", Author = "Philip Roth", ISBN10 = "0099399016", ISBN13 = "9780099399018", Description = "A disorder in which strongly-felt ethical and altruistic impulses are perpetually warring with extreme sexual longings, often of a perverse nature. Spielvogel says: 'Acts of exhibitionism, voyeurism, fetishism, auto-eroticism and oral coitus are plentiful; as a consequence of the patient's 'morality,' however, neither fantasy nor act issues in genuine sexual gratification, but rather in overriding feelings of shame, and the dread of retribution, particularly in the form of castration.' (Spielvogel, O. 'The Puzzled Penis, Internationale Zeitschrift fur Psychoanalyse, Vol. XXIV, p.909). It is believed by Spielvogel that many of the symptoms can be traced to the bonds obtaining in the mother-child relationship. ", NumberOfPages = 272, DatePublished = new DateModel(1998, 01, 03), Publisher = "Vintage Publishing", Rating = 3.5, NumberOfRatings = 21, NumberOfCopiesSold = 25, InStock = 45, Genre="Fiction", Price = 8.99},
                    new BookEntityModel { Title = "The Long Good-bye", Author = "Raymond Chandler", ISBN10 = "0241954363", ISBN13 = "9780241954362", Description = "Down-and-out drunk Terry Lennox has a problem: his millionaire wife is dead and he needs to get out of LA fast. So he turns to his only friend in the world: private investigator Philip Marlowe. He is willing to help a man down on his luck, but later Lennox commits suicide in Mexico and things start to turn nasty. Marlowe is drawn into a sordid crowd of adulterers and alcoholics in LA's Idle Valley, where the rich are suffering one big suntanned hangover. Marlowe is sure Lennox didn't kill his wife, but how many more stiffs will turn up before he gets to the truth?", NumberOfPages = 464, DatePublished = new DateModel(2011, 01, 24), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 32, NumberOfCopiesSold = 40, InStock = 43, Genre="Fiction", Price = 9.99},
                    new BookEntityModel { Title = "Sophie's Choice", Author = "William Styron", ISBN10 = "0099470446", ISBN13 = "9780099470441", Description = "In this extraordinary novel, Stingo, an inexperienced twenty-two year old Southerner, takes us back to the summer of 1947 and a boarding house in a leafy Brooklyn suburb. There he meets Nathan, a fiery Jewish intellectual; and Sophie, a beautiful and fragile Polish Catholic. Stingo is drawn into the heart of their passionate and destructive relationship as witness, confidant and supplicant. Ultimately, he arrives at the dark core of Sophie's past: her memories of pre-war Poland, the concentration camp and - the essence of her terrible secret - her choice. ", NumberOfPages = 656, DatePublished = new DateModel(2011, 07, 04), Publisher = "Vintage Publishing", Rating = 4.0, NumberOfRatings = 3, NumberOfCopiesSold = 10, InStock = 8, Genre="War", Price = 11.99},
                    new BookEntityModel { Title = "Goodbye To Berlin", Author = "Christopher Isherwood", ISBN10 = "0749390549", ISBN13 = "9780749390549", Description = "Set in the 1930s, Goodbye to Berlin evokes the glamour and sleaze, excess and repression of Berlin society. Isherwood shows the lives of people at threat from the rise of the Nazis: a wealthy Jewish heiress, Natalia Landauer, a gay couple, Peter and Otto, and an English upper-class waif, the divinely decadent Sally Bowles. ", NumberOfPages = 272, DatePublished = new DateModel(2003, 08, 14), Publisher = "Vintage Publishing", Rating = 4.0, NumberOfRatings = 11, NumberOfCopiesSold = 19, InStock = 72, Genre="Fiction", Price = 8.99},
                    new BookEntityModel { Title = "The Complete MAUS", Author = "Art Spiegelman", ISBN10 = "0141014083", ISBN13 = "9780141014081", Description = "The Pulitzer Prize-winning Maus tells the story of Vladek Spiegelman, a Jewish survivor of Hitler's Europe, and his son, a cartoonist coming to terms with his father's story. Maus approaches the unspeakable through the diminutive. Its form, the cartoon (the Nazis are cats, the Jews mice), shocks us out of any lingering sense of familiarity and succeeds in 'drawing us closer to the bleak heart of the Holocaust' (The New York Times).", NumberOfPages = 296, DatePublished = new DateModel(2003, 10, 02), Publisher = "Penguin Books Ltd", Rating = 4.5, NumberOfRatings = 32, NumberOfCopiesSold = 34, InStock = 17, Genre="War", Price = 17.99},
                    new BookEntityModel { Title = "Silent Spring", Author = "Rachel Carson", ISBN10 = "0618249060", ISBN13 = "9780618249060", Description = "Rachel Carson's `Silent Spring` was first published in three serialized excerpts in the `New Yorker` in June of 1962. The book appeared in September of that year and the outcry that followed its publication forced the banning of DDT and spurred revolutionary changes in the laws affecting our air, land, and water. Carson's passionate concern for the future of our planet reverberated powerfully throughout the world, and her eloquent book was instrumental in launching the environmental movement. It is without question one of the landmark books of the twentieth century. ", NumberOfPages = 400, DatePublished = new DateModel(2003, 10, 23), Publisher = "HOUGHTON MIFFLIN", Rating = 4.0, NumberOfRatings = 3, NumberOfCopiesSold = 4, InStock = 80, Genre="Educational", Price = 9.99},
                    new BookEntityModel { Title = "Shock of the New: Art and the Century of Change", Author = "Robert Hughes", ISBN10 = "0500275823", ISBN13 = "9780500275825", Description = "An illustrated 100-year history of modern art, from cubism to pop and avant-guard. . ", NumberOfPages = 448, DatePublished = new DateModel(2004, 04, 01), Publisher = "Thames & Hudson Ltd", Rating = 4.0, NumberOfRatings = 14, NumberOfCopiesSold = 73, InStock = 32, Genre="Educational", Price = 29.99},
                    new BookEntityModel { Title = "Let Us Now Praise Famous Men", Author = "Walker Evans", ISBN10 = "0141188499", ISBN13 = "9780141188492", Description = "In the summer of 1936, Agee and Evans set out on assignement for Fortune magazine to explore the daily lives of sharecroppers in the South. Their journey would prove an extraordinary collaboration and a watershed literary event when in 1941 Let Us Now Praise Famous Men was first published to enourmous critical acclaim. This unspairing record of place, of the people who shaped the land, and of the rhythm of their lives today stands as one of the most influential books of the twentieth century. ", NumberOfPages = 0, DatePublished = new DateModel(1996, 08, 15), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 38, NumberOfCopiesSold = 110, InStock = 31, Genre="Educational", Price = 16.99},
                    new BookEntityModel { Title = "Orientalism", Author = "Edward W. Said", ISBN10 = "0141187425", ISBN13 = "9780141187426", Description = "In this highly-acclaimed work, Edward Said surveys the history and nature of Western attitudes towards the East, considering orientalism as a powerful European ideological creation - a way for writers, philosophers and colonial administrators to deal with the 'otherness' of eastern culture, customs and beliefs. He traces this view through the writings of Homer, Nerval and Flaubert, Disraeli and Kipling, whose imaginative depictions have greatly contributed to the West's romantic and exotic picture of the Orient. Drawing on his own experiences as an Arab Palestinian living in the West, Said examines how these ideas can be a reflection of European imperialism and racism.", NumberOfPages = 432, DatePublished = new DateModel(2000, 05, 01), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 13, NumberOfCopiesSold = 16, InStock = 17, Genre="Educational", Price = 11.99},
                    new BookEntityModel { Title = "Eichmann in Jerusalem", Author = "Hannah Arendt", ISBN10 = "0143039881", ISBN13 = "9780143039884", Description = "Sparking a flurry of heated debate, Hannah Arendt's authoritative and stunning report on the trial of German Nazi SS leader Adolf Eichmann first appeared as a series of articles in The New Yorker in 1963. This revised edition includes material that came to light after the trial, as well as Arendt's postscript commenting on the controversy that arose over her book. A major journalistic triumph by an intellectual of singular influence, Eichmann in Jerusalem is as shocking as it is informative - a meticulous and unflinching look at one of the most unsettling (and unsettled) issues of the twentieth century.", NumberOfPages = 336, DatePublished = new DateModel(2011, 05, 22), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 32, NumberOfCopiesSold = 90, InStock = 8, Genre="Educational", Price = 9.99},
                    new BookEntityModel { Title = "The Affluent Society", Author = "John Kenneth Galbraith", ISBN10 = "0140285199", ISBN13 = "9780140285192", Description = "Why worship work and productivity if many of the goods we produce are superfluous - artificial 'needs' created by high-pressure advertising? Why begrudge expenditure on vital public works while ignoring waste and extravagance in the private sector of the economy? Classical economics was born in a harsh world of mass poverty, and has left us with a set of preconceptions ill-adapted to the realities of our own richer age. And so, too often, 'the bland lead the bland'. Our unfamiliar problems need a new approach, and the reception given to this famous book has shown the value of its fresh, lively ideas.", NumberOfPages = 288, DatePublished = new DateModel(1999, 08, 05), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 17, NumberOfCopiesSold = 23, InStock = 19, Genre="Educational", Price = 11.99},
                    new BookEntityModel { Title = "A Distant Mirror", Author = "Barbara W. Tuchman", ISBN10 = "0345349571", ISBN13 = "9780345349576", Description = "The 14th century gives us back two contradictory images: a glittering time of crusades and castles, cathedrals and chivalry, and a dark time of ferocity and spiritual agony, a world plunged into a chaos of war, fear and the Plague. Barbara Tuchman anatomizes the century, revealing both the great rhythms of history and the grain and texture of domestic life as it was lived. ", NumberOfPages = 704, DatePublished = new DateModel(1991, 09, 01), Publisher = "Random House USA Inc", Rating = 4.0, NumberOfRatings = 10, NumberOfCopiesSold = 20, InStock = 28, Genre="War", Price = 15.99},
                    new BookEntityModel { Title = "Black Lamb and Grey Falcon", Author = "Rebecca West", ISBN10 = "1841957879", ISBN13 = "9781841957876", Description = "First published in 1942, Rebecca West's epic masterpiece is widely regarded as the most illuminating book to have been written on the former state of Yugoslavia. It is a work of enduring value that remains essential for anyone attempting to understand the enigmatic history of the Balkan states, and the continuing friction in this fractured area of Europe. ", NumberOfPages = 1218, DatePublished = new DateModel(2006, 06, 27), Publisher = "Canongate Books Ltd", Rating = 4.0, NumberOfRatings = 12, NumberOfCopiesSold = 124, InStock = 50, Genre="Fiction", Price = .99},
                    new BookEntityModel { Title = "A Room of One's Own", Author = "Virginia Woolf", ISBN10 = "0141183535", ISBN13 = "9780141183534", Description = "Collecting two book-length essays, A Room of One's Own and Three Guineas is Virginia Woolf's most powerful feminist writing, justifying the need for women to possess intellectual freedom and financial independence. This Penguin Modern Classics edition is edited with an introduction and notes by Michele Barrett.", NumberOfPages = 112, DatePublished = new DateModel(2003, 03, 21), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 23, NumberOfCopiesSold = 114, InStock = 72, Genre="Fiction", Price = 6.99},
                    new BookEntityModel { Title = "The Diary of a Young Girl", Author = "Anne Frank", ISBN10 = "0141315180", ISBN13 = "9780141315188", Description = "In July 1942, thirteen-year-old Anne Frank and her family, fleeing the occupation, went into hiding in an Amsterdam warehouse. Over the next two years Anne vividly describes in her diary the frustrations of living in such close quarters, and her thoughts, feelings and longings as she grows up. Her diary ends abruptly when, in August 1944, they were all betrayed. ", NumberOfPages = 352, DatePublished = new DateModel(2011, 06, 17), Publisher = "Penguin Books Ltd", Rating = 4.0, NumberOfRatings = 37, NumberOfCopiesSold = 134, InStock = 69, Genre="Biography", Price = 8.99},
                
                };

                db.AddRange(initialBooks);
                db.SaveChanges();
            }
        }
    }
}
