using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using TheBookCave.Data;
using TheBookCave.Data.EntityModels.BookEntityModel;
using TheBookCave.Models;

namespace TheBookCave
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = BuildWebHost(args);
            SeedData();
            host.Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();

        public static void SeedData()
        {
            var db = new DataContext();

            if(db.Books.Any())
            {
                var initialBooks = new List<BookEntityModel>()
                {
                    new BookEntityModel { Title = "One Hundred Years of Solitude", Author = "Gabriel Garcia Marquez", ISBN10 = "014118499X", ISBN13 = "9780141184999", Description = "Equally tragic, joyful and comical, Gabriel Garcia Marquez's masterpiece of magical realism, One Hundred Years of Solitude is a seamless blend of fantasy and reality, translated from the Spanish by Gregory Rabassa in Penguin Modern Classics. Gabriel Garcia Marquez's great masterpiece is the story of seven generations of the Buendia family and of Macondo, the town they have built. Though little more than a settlement surrounded by mountains, Macondo has its wars and disasters, even its wonders and miracles. A microcosm of Columbian life, its secrets lie hidden, encoded in a book and only Aureliano Buendia can fathom its mysteries and reveal its shrouded destiny. Blending political reality with magic realism, fantasy with comic invention, One Hundred Years of Solitude is one of the most daringly original works of the twentieth century. Gabriel Garcia Marquez (b. 1928) was born in Aracataca, Colombia. He is the author of several novels, including Leaf Storm (1955), One Hundred Years of Solitude (1967), The Autumn of the Patriarch (1975), Chronicle of a Death Foretold (1981) and The General in His Labyrinth (1989).", NumberOfPages = 432, DatePublished = new DateModel(2000, 31, 08), Publisher = "Penguin Books Ltd", Rating = 4.5, NumberOfRatings = 13, NumberOfCopiesSold = 120, InStock = 8, Genre="Romance", Price = 9.99},
                    new BookEntityModel { Title = "Wuthering Heights", Author = "Emily Brotne", ISBN10 = "0141439556", ISBN13 = "9780141439556", Description = "Lockwood, the new tenant of Thrushcross Grange, situated on the bleak Yorkshire moors, is forced to seek shelter one night at Wuthering Heights, the home of his landlord. There he discovers the history of the tempestuous events that took place years before; of the intense relationship between the gypsy foundling Heathcliff and Catherine Earnshaw; and how Catherine, forced to choose between passionate, tortured Heathcliff and gentle, well-bred Edgar Linton, surrendered to the expectations of her class. As Heathcliff's bitterness and vengeance at his betrayal is visited upon the next generation, their innocent heirs must struggle to escape the legacy of the past.", NumberOfPages = 416, DatePublished = new DateModel(2004, 11, 11), Publisher = "Penguin Books Ltd", Rating = 3.5, NumberOfRatings = 14, NumberOfCopiesSold = 143, InStock = 13, Genre="Romance", Price = 7.99},
                    new BookEntityModel { Title = "Pride and Prejudice", Author = "Jane Austen", ISBN10 = "0141199075", ISBN13 = "9780141199078", Description = "When Elizabeth Bennet first meets eligible bachelor Fitzwilliam Darcy, she thinks him arrogant and conceited; he is indifferent to her good looks and lively mind. When she later discovers that Darcy has involved himself in the troubled relationship between his friend Bingley and her beloved sister Jane, she is determined to dislike him more than ever. In the sparkling comedy of manners that follows, Jane Austen shows the folly of judging by first impressions and superbly evokes the friendships, gossip and snobberies of provincial middle-class life.", NumberOfPages = 416, DatePublished = new DateModel(2012, 12, 06), Publisher = "Penguin Books Ltd", Rating = 4.5, NumberOfRatings = 16, NumberOfCopiesSold = 253, InStock = 17, Genre="Children", Price = 6.99},
                    new BookEntityModel { Title = "A Brief History Of Time : From Big Bang To Black Holes", Author = "Stephen Hawking", ISBN10 = "0857501003", ISBN13 = "9780857501004", Description = "These are just some of the questions considered in the internationally acclaimed masterpiece by the world renowned physicist - generally considered to have been one of the world's greatest thinkers. It begins by reviewing the great theories of the cosmos from Newton to Einstein, before delving into the secrets which still lie at the heart of space and time, from the Big Bang to black holes, via spiral galaxies and strong theory. To this day A Brief History of Time remains a staple of the scientific canon, and its succinct and clear language continues to introduce millions to the universe and its wonders.", NumberOfPages = 272, DatePublished = new DateModel(2015, 02, 05), Publisher = "Transworld Publishers Ltd", Rating = 4.5, NumberOfRatings = 45, NumberOfCopiesSold = 191, InStock = 1, Genre="Learning", Price = 9.59},
                    new BookEntityModel { Title = "Our Mutual Friend", Author = "Charles Dickens", ISBN10 = "0199536252", ISBN13 = "0199536252", Description = "Following his father's death John Harmon returns to London to claim his inheritance, but he finds he is eligible only if he marries Bella Wilfur. To observe her character he assumes another identity and secures work with his father's foreman, Mr Boffin, who is also Bella's guardian. Disguise and concealment play an important role in the novel and individual identity is examined within the wider setting of London life: in the 1860s the city was aflame with spiralling financial speculation while thousands of homeless scratched a living from the detritus of the more fortunate-indeed John Harmon's father has amassed his wealth by recycling waste. This edition includes extensive explanatory notes and significant manuscript variants. ABOUT THE SERIES: For over 100 years Oxford World's Classics has made available the widest range of literature from around the globe. Each affordable volume reflects Oxford's commitment to scholarship, providing the most accurate text plus a wealth of other valuable features, including expert introductions by leading authorities, helpful notes to clarify the text, up-to-date bibliographies for further study, and much more.", NumberOfPages = 880, DatePublished = new DateModel(2009, 15, 01), Publisher = "Oxford University Press", Rating = 4, NumberOfRatings = 22, NumberOfCopiesSold = 44, InStock = 40, Genre="Adventure", Price = 11.99},
                    new BookEntityModel { Title = "Breakfast at Tiffany's", Author = "Truman Capote", ISBN10 = "0141182792", ISBN13 = "9780141182797", Description = "Immortalised by Audrey Hepburn's sparkling performance in the 1961 film of the same name, `Breakfast at Tiffany's` is Truman Capote's timeless portrait of tragicomic cultural icon Holly Golightly, published in `Penguin Modern Classics`. It's New York in the 1940s, where the martinis flow from cocktail hour till breakfast at Tiffany's. And nice girls don't, except, of course, for Holly Golightly: glittering socialite traveller, generally upwards, sometimes sideways and once in a while - down. Pursued by to Salvatore 'Sally' Tomato, the Mafia sugar-daddy doing life in Sing Sing and 'Rusty' Trawler, the blue-chinned, cuff-shooting millionaire man about women about town, Holly is a fragile eyeful of tawny hair and turned-up nose, a heart-breaker, a perplexer, a traveller, a tease. She is irrepressibly 'top banana in the shock deparment', and one of the shining flowers of American fiction.  This edition also contains three stories: `House of Flowers`, `A Diamond Guitar` and `A Christmas Memory`.", NumberOfPages = 160, DatePublished = new DateModel(2000, 04, 27), Publisher = "Penguin Books Ltd", Rating = 3.5, NumberOfRatings = 30, NumberOfCopiesSold = 195, InStock = 23, Genre="Adventure", Price = 7.99},
                    new BookEntityModel { Title = "The Wonderful Story of Henry Sugar and Six More", Author = "Rolald Dahl", ISBN10 = "0241955785", ISBN13 = "9780241955789", Description = "Enter a brilliant, sinister and wholly unpredictable world. Here you will find the suggestion of other-worldly goings on in a dark story about a swan and a boy; the surprising tale of a wealthy young wastrel who suddenly develops a remarkable new ability; and meet the hitchhiker whose light-fingers save the day.", NumberOfPages = 256, DatePublished = new DateModel(2011, 10, 27), Publisher = "Penguin Books Ltd", Rating = 4.5, NumberOfRatings = 22, NumberOfCopiesSold = 133, InStock = 16, Genre="children", Price = 9.99},
                    new BookEntityModel { Title = "Madame Bovary : Provincial Manners", Author = "Gustave Flaubert", ISBN10 = "0199535655", ISBN13 = "9780199535651", Description = "'Would this misery go on forever? Was there no escape? And yet she was every bit as good as all those other women who led happy lives!' When Emma Rouault marries Charles Bovary she imagines she will pass into the life of luxury and passion that she reads about in sentimental novels and women's magazines. But Charles is a dull country doctor, and provincial life is very different from the romantic excitement for which she yearns. In her quest to realize her dreams she takes a lover, and begins a devastating spiral into deceit and despair.", NumberOfPages = 386, DatePublished = new DateModel(2008, 08, 29), Publisher = "Oxford University Press", Rating = 3, NumberOfRatings = 25, NumberOfCopiesSold = 93, InStock = 8, Genre="Adventure", Price = 8.99},
                    new BookEntityModel { Title = "The Picture of Dorian Gray", Author = "Oscar Wilde", ISBN10 = "0141442468", ISBN13 = "9780141442464", Description = "Enthralled by his own exquisite portrait, Dorian Gray exchanges his soul for eternal youth and beauty. Influenced by his friend Lord Henry Wotton, he is drawn into a corrupt double life; indulging his desires in secret while remaining a gentleman in the eyes of polite society. Only his portrait bears the traces of his decadence. The novel was a succes de scandale and the book was later used as evidence against Wilde at the Old Bailey in 1895. It has lost none of its power to fascinate and disturb.", NumberOfPages = 304, DatePublished = new DateModel(2011, 06, 21), Publisher = "Penguin Books Ltd", Rating = 4, NumberOfRatings = 19, NumberOfCopiesSold = 240, InStock = 56, Genre="Horror", Price = 14.99},
                };

                db.AddRange(initialBooks);
                db.SaveChanges();
            }
        }
    }
}
